package com.ylzh.onlineexam.mapper;

import com.ylzh.onlineexam.entity.BizArticle;
import java.util.List;

public interface BizArticleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_article
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_article
     *
     * @mbggenerated
     */
    int insert(BizArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_article
     *
     * @mbggenerated
     */
    BizArticle selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_article
     *
     * @mbggenerated
     */
    List<BizArticle> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_article
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BizArticle record);
}