package com.ylzh.onlineexam.mapper;

import com.ylzh.onlineexam.entity.BizArticleLook;
import com.ylzh.onlineexam.util.MapperUtil;
import org.apache.ibatis.annotations.Param;

import java.util.Date;
import java.util.List;

public interface BizArticleLookMapper extends MapperUtil<BizArticleLook> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_article_look
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(@Param("id") Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_article_look
     *
     * @mbggenerated
     */
    int insert(BizArticleLook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_article_look
     *
     * @mbggenerated
     */
    BizArticleLook selectByPrimaryKey(@Param("id") Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_article_look
     *
     * @mbggenerated
     */
    List<BizArticleLook> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_article_look
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BizArticleLook record);

    int checkArticleLook(@Param("articleId") Integer articleId, @Param("userIp") String userIp, @Param("lookTime") Date lookTime);
}