package com.ylzh.onlineexam.mapper;

import com.ylzh.onlineexam.entity.BizArticleLook;
import java.util.List;

public interface BizArticleLookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_article_look
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_article_look
     *
     * @mbggenerated
     */
    int insert(BizArticleLook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_article_look
     *
     * @mbggenerated
     */
    BizArticleLook selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_article_look
     *
     * @mbggenerated
     */
    List<BizArticleLook> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_article_look
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BizArticleLook record);
}