package com.ylzh.onlineexam.mapper;

import com.ylzh.onlineexam.entity.BizArticleTags;
import java.util.List;

public interface BizArticleTagsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_article_tags
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_article_tags
     *
     * @mbggenerated
     */
    int insert(BizArticleTags record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_article_tags
     *
     * @mbggenerated
     */
    BizArticleTags selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_article_tags
     *
     * @mbggenerated
     */
    List<BizArticleTags> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_article_tags
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BizArticleTags record);
}