package com.ylzh.onlineexam.mapper;

import com.ylzh.onlineexam.entity.BizComment;
import java.util.List;

public interface BizCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_comment
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_comment
     *
     * @mbggenerated
     */
    int insert(BizComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_comment
     *
     * @mbggenerated
     */
    BizComment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_comment
     *
     * @mbggenerated
     */
    List<BizComment> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_comment
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BizComment record);
}