package com.ylzh.onlineexam.mapper;

import com.ylzh.onlineexam.entity.BizLove;
import java.util.List;

public interface BizLoveMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_love
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_love
     *
     * @mbggenerated
     */
    int insert(BizLove record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_love
     *
     * @mbggenerated
     */
    BizLove selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_love
     *
     * @mbggenerated
     */
    List<BizLove> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_love
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BizLove record);
}