package com.ylzh.onlineexam.mapper;

import com.ylzh.onlineexam.entity.BizLink;
import java.util.List;

public interface BizLinkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_link
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_link
     *
     * @mbggenerated
     */
    int insert(BizLink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_link
     *
     * @mbggenerated
     */
    BizLink selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_link
     *
     * @mbggenerated
     */
    List<BizLink> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_link
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BizLink record);
}