package com.ylzh.onlineexam.mapper;

import com.ylzh.onlineexam.entity.BizSiteInfo;
import java.util.List;

public interface BizSiteInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_site_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_site_info
     *
     * @mbggenerated
     */
    int insert(BizSiteInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_site_info
     *
     * @mbggenerated
     */
    BizSiteInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_site_info
     *
     * @mbggenerated
     */
    List<BizSiteInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_site_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BizSiteInfo record);
}