package com.ylzh.onlineexam.mapper;

import com.ylzh.onlineexam.entity.BizTheme;
import java.util.List;

public interface BizThemeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_theme
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_theme
     *
     * @mbggenerated
     */
    int insert(BizTheme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_theme
     *
     * @mbggenerated
     */
    BizTheme selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_theme
     *
     * @mbggenerated
     */
    List<BizTheme> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_theme
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BizTheme record);
}