package com.ylzh.onlineexam.mapper;

import com.ylzh.onlineexam.entity.ExamQuestion;
import java.util.List;

public interface ExamQuestionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_question
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_question
     *
     * @mbggenerated
     */
    int insert(ExamQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_question
     *
     * @mbggenerated
     */
    ExamQuestion selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_question
     *
     * @mbggenerated
     */
    List<ExamQuestion> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_question
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ExamQuestion record);

    int deleteByExampleId(Integer examId);
}