package com.ylzh.onlineexam.mapper;

import com.ylzh.onlineexam.entity.Subject;
import com.ylzh.onlineexam.util.MapperUtil;

import java.util.List;

public interface SubjectMapper extends MapperUtil<Subject> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject
     *
     * @mbggenerated
     */
    int insert(Subject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject
     *
     * @mbggenerated
     */
    Subject selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject
     *
     * @mbggenerated
     */
    List<Subject> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Subject record);

    List<Subject> selectSubjects(Subject subject);

    int deleteBatch(Integer[] ids);

    Subject selectById(Integer id);
}