server:
  port: 8989
spring:
  thymeleaf:
    # 配置视图路径前缀
    prefix: classpath:/templates/
    # 配置视图路径后缀
    suffix: .html
    mode: html
    # 关闭缓存 修改视图 刷新浏览器就显示 开发阶段务必关闭缓存 (=false)
    cache: false
  datasource:
    username: root
    password: 123456
    # 东8区的Hongkong、Asia/Shanghai或者Asia/Hongkong作为参数
    url: jdbc:mysql://127.0.0.1:3306/onlineexam?useUnicode=true&characterEncoding=utf8&serverTimezone=Hongkong
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true