server:
  port: 8989
mybatis:
  type-aliases-package: com.ylzh.onlineexam.entity
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  #config-location:  classpath:/mybatis/config/mybatis-config.xml
spring:
  #thymeleaf start
  thymeleaf:
    # 配置视图路径前缀
    prefix: classpath:/templates/
    # 配置视图路径后缀
    suffix: .html
    mode: html
    # 关闭缓存 修改视图 刷新浏览器就显示 开发阶段务必关闭缓存 (=false)
    cache: false
    encoding: UTF-8
    servlet:
      content-type: text/html
  #thymeleaf end
  # mapper-locations 是配置我们mapper.xml文件的位置，我们把它配置在/src/main/resource/mybatis/mapper目录下。
  # config-locations 是配置mybatis-confg.xml文件的位置。我们把它配置在/src/main/resource/mybatis/config目录下。
  datasource:
    username: root
    password: 123456
    # 东8区的Hongkong、Asia/Shanghai或者Asia/Hongkong作为参数
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/onlineexam?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Hongkong
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 初始化大小，最小保持连接数，最大活跃连接数
    initialSize: 1
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    filters: stat,wall,slf4j
  redis:
    host: localhost
    port: 6379
    password: 123456
    timeout: 5000
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  activemq:
    broker-url:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
mapper:
  mappers: com.ylzh.onlineexam.util.MapperUtil
  not-empty: false
  identity: MYSQL
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
# log system
logging:
  config: classpath:logback-spring.xml
  path: D:/nmyslog/nmys