package com.ylzh.onlineexam.entity;

import java.io.Serializable;
import java.util.Date;

public class BizArticle implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_article.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_article.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_article.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_article.author
     *
     * @mbggenerated
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_article.cover_image
     *
     * @mbggenerated
     */
    private String coverImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_article.qrcode_path
     *
     * @mbggenerated
     */
    private String qrcodePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_article.is_markdown
     *
     * @mbggenerated
     */
    private Boolean isMarkdown;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_article.top
     *
     * @mbggenerated
     */
    private Boolean top;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_article.category_id
     *
     * @mbggenerated
     */
    private Integer categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_article.status
     *
     * @mbggenerated
     */
    private Boolean status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_article.recommended
     *
     * @mbggenerated
     */
    private Boolean recommended;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_article.slider
     *
     * @mbggenerated
     */
    private Boolean slider;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_article.slider_img
     *
     * @mbggenerated
     */
    private String sliderImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_article.original
     *
     * @mbggenerated
     */
    private Boolean original;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_article.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_article.keywords
     *
     * @mbggenerated
     */
    private String keywords;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_article.comment
     *
     * @mbggenerated
     */
    private Boolean comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_article.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_article.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_article.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_article.content_md
     *
     * @mbggenerated
     */
    private String contentMd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table biz_article
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_article.id
     *
     * @return the value of biz_article.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_article.id
     *
     * @param id the value for biz_article.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_article.title
     *
     * @return the value of biz_article.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_article.title
     *
     * @param title the value for biz_article.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_article.user_id
     *
     * @return the value of biz_article.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_article.user_id
     *
     * @param userId the value for biz_article.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_article.author
     *
     * @return the value of biz_article.author
     *
     * @mbggenerated
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_article.author
     *
     * @param author the value for biz_article.author
     *
     * @mbggenerated
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_article.cover_image
     *
     * @return the value of biz_article.cover_image
     *
     * @mbggenerated
     */
    public String getCoverImage() {
        return coverImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_article.cover_image
     *
     * @param coverImage the value for biz_article.cover_image
     *
     * @mbggenerated
     */
    public void setCoverImage(String coverImage) {
        this.coverImage = coverImage == null ? null : coverImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_article.qrcode_path
     *
     * @return the value of biz_article.qrcode_path
     *
     * @mbggenerated
     */
    public String getQrcodePath() {
        return qrcodePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_article.qrcode_path
     *
     * @param qrcodePath the value for biz_article.qrcode_path
     *
     * @mbggenerated
     */
    public void setQrcodePath(String qrcodePath) {
        this.qrcodePath = qrcodePath == null ? null : qrcodePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_article.is_markdown
     *
     * @return the value of biz_article.is_markdown
     *
     * @mbggenerated
     */
    public Boolean getIsMarkdown() {
        return isMarkdown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_article.is_markdown
     *
     * @param isMarkdown the value for biz_article.is_markdown
     *
     * @mbggenerated
     */
    public void setIsMarkdown(Boolean isMarkdown) {
        this.isMarkdown = isMarkdown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_article.top
     *
     * @return the value of biz_article.top
     *
     * @mbggenerated
     */
    public Boolean getTop() {
        return top;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_article.top
     *
     * @param top the value for biz_article.top
     *
     * @mbggenerated
     */
    public void setTop(Boolean top) {
        this.top = top;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_article.category_id
     *
     * @return the value of biz_article.category_id
     *
     * @mbggenerated
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_article.category_id
     *
     * @param categoryId the value for biz_article.category_id
     *
     * @mbggenerated
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_article.status
     *
     * @return the value of biz_article.status
     *
     * @mbggenerated
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_article.status
     *
     * @param status the value for biz_article.status
     *
     * @mbggenerated
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_article.recommended
     *
     * @return the value of biz_article.recommended
     *
     * @mbggenerated
     */
    public Boolean getRecommended() {
        return recommended;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_article.recommended
     *
     * @param recommended the value for biz_article.recommended
     *
     * @mbggenerated
     */
    public void setRecommended(Boolean recommended) {
        this.recommended = recommended;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_article.slider
     *
     * @return the value of biz_article.slider
     *
     * @mbggenerated
     */
    public Boolean getSlider() {
        return slider;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_article.slider
     *
     * @param slider the value for biz_article.slider
     *
     * @mbggenerated
     */
    public void setSlider(Boolean slider) {
        this.slider = slider;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_article.slider_img
     *
     * @return the value of biz_article.slider_img
     *
     * @mbggenerated
     */
    public String getSliderImg() {
        return sliderImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_article.slider_img
     *
     * @param sliderImg the value for biz_article.slider_img
     *
     * @mbggenerated
     */
    public void setSliderImg(String sliderImg) {
        this.sliderImg = sliderImg == null ? null : sliderImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_article.original
     *
     * @return the value of biz_article.original
     *
     * @mbggenerated
     */
    public Boolean getOriginal() {
        return original;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_article.original
     *
     * @param original the value for biz_article.original
     *
     * @mbggenerated
     */
    public void setOriginal(Boolean original) {
        this.original = original;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_article.description
     *
     * @return the value of biz_article.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_article.description
     *
     * @param description the value for biz_article.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_article.keywords
     *
     * @return the value of biz_article.keywords
     *
     * @mbggenerated
     */
    public String getKeywords() {
        return keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_article.keywords
     *
     * @param keywords the value for biz_article.keywords
     *
     * @mbggenerated
     */
    public void setKeywords(String keywords) {
        this.keywords = keywords == null ? null : keywords.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_article.comment
     *
     * @return the value of biz_article.comment
     *
     * @mbggenerated
     */
    public Boolean getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_article.comment
     *
     * @param comment the value for biz_article.comment
     *
     * @mbggenerated
     */
    public void setComment(Boolean comment) {
        this.comment = comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_article.create_time
     *
     * @return the value of biz_article.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_article.create_time
     *
     * @param createTime the value for biz_article.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_article.update_time
     *
     * @return the value of biz_article.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_article.update_time
     *
     * @param updateTime the value for biz_article.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_article.content
     *
     * @return the value of biz_article.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_article.content
     *
     * @param content the value for biz_article.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_article.content_md
     *
     * @return the value of biz_article.content_md
     *
     * @mbggenerated
     */
    public String getContentMd() {
        return contentMd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_article.content_md
     *
     * @param contentMd the value for biz_article.content_md
     *
     * @mbggenerated
     */
    public void setContentMd(String contentMd) {
        this.contentMd = contentMd == null ? null : contentMd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_article
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", title=").append(title);
        sb.append(", userId=").append(userId);
        sb.append(", author=").append(author);
        sb.append(", coverImage=").append(coverImage);
        sb.append(", qrcodePath=").append(qrcodePath);
        sb.append(", isMarkdown=").append(isMarkdown);
        sb.append(", top=").append(top);
        sb.append(", categoryId=").append(categoryId);
        sb.append(", status=").append(status);
        sb.append(", recommended=").append(recommended);
        sb.append(", slider=").append(slider);
        sb.append(", sliderImg=").append(sliderImg);
        sb.append(", original=").append(original);
        sb.append(", description=").append(description);
        sb.append(", keywords=").append(keywords);
        sb.append(", comment=").append(comment);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", content=").append(content);
        sb.append(", contentMd=").append(contentMd);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}