package com.ylzh.onlineexam.entity;

import com.ylzh.onlineexam.vo.base.BaseVO;

import java.util.List;

import javax.persistence.Transient;


public class BizCategory extends BaseVO {
    private Integer pid;
    private String name;
    private String description;
    private Integer sort;
    private Integer status;
    private String icon;


    @Transient
    private BizCategory parent;
    @Transient
    private List<BizCategory> nodes;

    public Integer getPid() {
        return pid;
    }

    public void setPid(Integer pid) {
        this.pid = pid;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Integer getSort() {
        return sort;
    }

    public void setSort(Integer sort) {
        this.sort = sort;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public String getIcon() {
        return icon;
    }

    public void setIcon(String icon) {
        this.icon = icon;
    }

    public BizCategory getParent() {
        return parent;
    }

    public void setParent(BizCategory parent) {
        this.parent = parent;
    }

    public List<BizCategory> getNodes() {
        return nodes;
    }

    public void setNodes(List<BizCategory> nodes) {
        this.nodes = nodes;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_category
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(getId());
        sb.append(", pid=").append(pid);
        sb.append(", name=").append(name);
        sb.append(", description=").append(description);
        sb.append(", sort=").append(sort);
        sb.append(", icon=").append(icon);
        sb.append(", status=").append(status);
        sb.append(", createTime=").append(getCreateTime());
        sb.append(", updateTime=").append(getUpdateTime());
        sb.append("]");
        return sb.toString();
    }
}