package com.ylzh.onlineexam.entity;

import java.io.Serializable;
import java.util.Date;

public class BizComment implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_comment.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_comment.sid
     *
     * @mbggenerated
     */
    private Integer sid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_comment.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_comment.pid
     *
     * @mbggenerated
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_comment.qq
     *
     * @mbggenerated
     */
    private String qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_comment.nickname
     *
     * @mbggenerated
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_comment.avatar
     *
     * @mbggenerated
     */
    private String avatar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_comment.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_comment.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_comment.status
     *
     * @mbggenerated
     */
    private Boolean status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_comment.ip
     *
     * @mbggenerated
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_comment.lng
     *
     * @mbggenerated
     */
    private String lng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_comment.lat
     *
     * @mbggenerated
     */
    private String lat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_comment.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_comment.os
     *
     * @mbggenerated
     */
    private String os;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_comment.os_short_name
     *
     * @mbggenerated
     */
    private String osShortName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_comment.browser
     *
     * @mbggenerated
     */
    private String browser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_comment.browser_short_name
     *
     * @mbggenerated
     */
    private String browserShortName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_comment.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_comment.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_comment.support
     *
     * @mbggenerated
     */
    private Integer support;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_comment.oppose
     *
     * @mbggenerated
     */
    private Integer oppose;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_comment.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_comment.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table biz_comment
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_comment.id
     *
     * @return the value of biz_comment.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_comment.id
     *
     * @param id the value for biz_comment.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_comment.sid
     *
     * @return the value of biz_comment.sid
     *
     * @mbggenerated
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_comment.sid
     *
     * @param sid the value for biz_comment.sid
     *
     * @mbggenerated
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_comment.user_id
     *
     * @return the value of biz_comment.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_comment.user_id
     *
     * @param userId the value for biz_comment.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_comment.pid
     *
     * @return the value of biz_comment.pid
     *
     * @mbggenerated
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_comment.pid
     *
     * @param pid the value for biz_comment.pid
     *
     * @mbggenerated
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_comment.qq
     *
     * @return the value of biz_comment.qq
     *
     * @mbggenerated
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_comment.qq
     *
     * @param qq the value for biz_comment.qq
     *
     * @mbggenerated
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_comment.nickname
     *
     * @return the value of biz_comment.nickname
     *
     * @mbggenerated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_comment.nickname
     *
     * @param nickname the value for biz_comment.nickname
     *
     * @mbggenerated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_comment.avatar
     *
     * @return the value of biz_comment.avatar
     *
     * @mbggenerated
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_comment.avatar
     *
     * @param avatar the value for biz_comment.avatar
     *
     * @mbggenerated
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_comment.email
     *
     * @return the value of biz_comment.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_comment.email
     *
     * @param email the value for biz_comment.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_comment.url
     *
     * @return the value of biz_comment.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_comment.url
     *
     * @param url the value for biz_comment.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_comment.status
     *
     * @return the value of biz_comment.status
     *
     * @mbggenerated
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_comment.status
     *
     * @param status the value for biz_comment.status
     *
     * @mbggenerated
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_comment.ip
     *
     * @return the value of biz_comment.ip
     *
     * @mbggenerated
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_comment.ip
     *
     * @param ip the value for biz_comment.ip
     *
     * @mbggenerated
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_comment.lng
     *
     * @return the value of biz_comment.lng
     *
     * @mbggenerated
     */
    public String getLng() {
        return lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_comment.lng
     *
     * @param lng the value for biz_comment.lng
     *
     * @mbggenerated
     */
    public void setLng(String lng) {
        this.lng = lng == null ? null : lng.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_comment.lat
     *
     * @return the value of biz_comment.lat
     *
     * @mbggenerated
     */
    public String getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_comment.lat
     *
     * @param lat the value for biz_comment.lat
     *
     * @mbggenerated
     */
    public void setLat(String lat) {
        this.lat = lat == null ? null : lat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_comment.address
     *
     * @return the value of biz_comment.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_comment.address
     *
     * @param address the value for biz_comment.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_comment.os
     *
     * @return the value of biz_comment.os
     *
     * @mbggenerated
     */
    public String getOs() {
        return os;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_comment.os
     *
     * @param os the value for biz_comment.os
     *
     * @mbggenerated
     */
    public void setOs(String os) {
        this.os = os == null ? null : os.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_comment.os_short_name
     *
     * @return the value of biz_comment.os_short_name
     *
     * @mbggenerated
     */
    public String getOsShortName() {
        return osShortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_comment.os_short_name
     *
     * @param osShortName the value for biz_comment.os_short_name
     *
     * @mbggenerated
     */
    public void setOsShortName(String osShortName) {
        this.osShortName = osShortName == null ? null : osShortName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_comment.browser
     *
     * @return the value of biz_comment.browser
     *
     * @mbggenerated
     */
    public String getBrowser() {
        return browser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_comment.browser
     *
     * @param browser the value for biz_comment.browser
     *
     * @mbggenerated
     */
    public void setBrowser(String browser) {
        this.browser = browser == null ? null : browser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_comment.browser_short_name
     *
     * @return the value of biz_comment.browser_short_name
     *
     * @mbggenerated
     */
    public String getBrowserShortName() {
        return browserShortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_comment.browser_short_name
     *
     * @param browserShortName the value for biz_comment.browser_short_name
     *
     * @mbggenerated
     */
    public void setBrowserShortName(String browserShortName) {
        this.browserShortName = browserShortName == null ? null : browserShortName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_comment.content
     *
     * @return the value of biz_comment.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_comment.content
     *
     * @param content the value for biz_comment.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_comment.remark
     *
     * @return the value of biz_comment.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_comment.remark
     *
     * @param remark the value for biz_comment.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_comment.support
     *
     * @return the value of biz_comment.support
     *
     * @mbggenerated
     */
    public Integer getSupport() {
        return support;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_comment.support
     *
     * @param support the value for biz_comment.support
     *
     * @mbggenerated
     */
    public void setSupport(Integer support) {
        this.support = support;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_comment.oppose
     *
     * @return the value of biz_comment.oppose
     *
     * @mbggenerated
     */
    public Integer getOppose() {
        return oppose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_comment.oppose
     *
     * @param oppose the value for biz_comment.oppose
     *
     * @mbggenerated
     */
    public void setOppose(Integer oppose) {
        this.oppose = oppose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_comment.create_time
     *
     * @return the value of biz_comment.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_comment.create_time
     *
     * @param createTime the value for biz_comment.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_comment.update_time
     *
     * @return the value of biz_comment.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_comment.update_time
     *
     * @param updateTime the value for biz_comment.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_comment
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", sid=").append(sid);
        sb.append(", userId=").append(userId);
        sb.append(", pid=").append(pid);
        sb.append(", qq=").append(qq);
        sb.append(", nickname=").append(nickname);
        sb.append(", avatar=").append(avatar);
        sb.append(", email=").append(email);
        sb.append(", url=").append(url);
        sb.append(", status=").append(status);
        sb.append(", ip=").append(ip);
        sb.append(", lng=").append(lng);
        sb.append(", lat=").append(lat);
        sb.append(", address=").append(address);
        sb.append(", os=").append(os);
        sb.append(", osShortName=").append(osShortName);
        sb.append(", browser=").append(browser);
        sb.append(", browserShortName=").append(browserShortName);
        sb.append(", content=").append(content);
        sb.append(", remark=").append(remark);
        sb.append(", support=").append(support);
        sb.append(", oppose=").append(oppose);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}