package com.ylzh.onlineexam.entity;


import com.ylzh.onlineexam.vo.base.BaseVO;

public class BizLove extends BaseVO {
    private Integer bizId;
    private Integer bizType;
    private String userId;
    private String userIp;
    private Integer status;

    public Integer getBizId() {
        return bizId;
    }

    public void setBizId(Integer bizId) {
        this.bizId = bizId;
    }

    public Integer getBizType() {
        return bizType;
    }

    public void setBizType(Integer bizType) {
        this.bizType = bizType;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getUserIp() {
        return userIp;
    }

    public void setUserIp(String userIp) {
        this.userIp = userIp;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_love
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(getId());
        sb.append(", bizId=").append(bizId);
        sb.append(", bizType=").append(bizType);
        sb.append(", userId=").append(userId);
        sb.append(", userIp=").append(userIp);
        sb.append(", status=").append(status);
        sb.append(", createTime=").append(getCreateTime());
        sb.append(", updateTime=").append(getUpdateTime());
        sb.append("]");
        return sb.toString();
    }
}