package com.ylzh.onlineexam.entity;

import com.ylzh.onlineexam.vo.base.BaseVO;

import java.util.Date;

public class BizSiteInfo extends BaseVO {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_site_info.site_name
     *
     * @mbggenerated
     */
    private String siteName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_site_info.site_desc
     *
     * @mbggenerated
     */
    private String siteDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_site_info.site_pic
     *
     * @mbggenerated
     */
    private String sitePic;



    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_site_info.site_name
     *
     * @return the value of biz_site_info.site_name
     *
     * @mbggenerated
     */
    public String getSiteName() {
        return siteName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_site_info.site_name
     *
     * @param siteName the value for biz_site_info.site_name
     *
     * @mbggenerated
     */
    public void setSiteName(String siteName) {
        this.siteName = siteName == null ? null : siteName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_site_info.site_desc
     *
     * @return the value of biz_site_info.site_desc
     *
     * @mbggenerated
     */
    public String getSiteDesc() {
        return siteDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_site_info.site_desc
     *
     * @param siteDesc the value for biz_site_info.site_desc
     *
     * @mbggenerated
     */
    public void setSiteDesc(String siteDesc) {
        this.siteDesc = siteDesc == null ? null : siteDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_site_info.site_pic
     *
     * @return the value of biz_site_info.site_pic
     *
     * @mbggenerated
     */
    public String getSitePic() {
        return sitePic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_site_info.site_pic
     *
     * @param sitePic the value for biz_site_info.site_pic
     *
     * @mbggenerated
     */
    public void setSitePic(String sitePic) {
        this.sitePic = sitePic == null ? null : sitePic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_site_info
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(getId());
        sb.append(", siteName=").append(siteName);
        sb.append(", siteDesc=").append(siteDesc);
        sb.append(", sitePic=").append(sitePic);
        sb.append(", createTime=").append(getCreateTime());
        sb.append(", updateTime=").append(getUpdateTime());
        sb.append("]");
        return sb.toString();
    }
}