package com.ylzh.onlineexam.entity;

import java.io.Serializable;
import java.util.Date;

public class Grade implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.exam_id
     *
     * @mbggenerated
     */
    private String examId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.result
     *
     * @mbggenerated
     */
    private Integer result;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.auto_result
     *
     * @mbggenerated
     */
    private Integer autoResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.manul_result
     *
     * @mbggenerated
     */
    private Integer manulResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.answer_json
     *
     * @mbggenerated
     */
    private String answerJson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table grade
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.id
     *
     * @return the value of grade.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.id
     *
     * @param id the value for grade.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.user_id
     *
     * @return the value of grade.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.user_id
     *
     * @param userId the value for grade.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.exam_id
     *
     * @return the value of grade.exam_id
     *
     * @mbggenerated
     */
    public String getExamId() {
        return examId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.exam_id
     *
     * @param examId the value for grade.exam_id
     *
     * @mbggenerated
     */
    public void setExamId(String examId) {
        this.examId = examId == null ? null : examId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.result
     *
     * @return the value of grade.result
     *
     * @mbggenerated
     */
    public Integer getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.result
     *
     * @param result the value for grade.result
     *
     * @mbggenerated
     */
    public void setResult(Integer result) {
        this.result = result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.auto_result
     *
     * @return the value of grade.auto_result
     *
     * @mbggenerated
     */
    public Integer getAutoResult() {
        return autoResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.auto_result
     *
     * @param autoResult the value for grade.auto_result
     *
     * @mbggenerated
     */
    public void setAutoResult(Integer autoResult) {
        this.autoResult = autoResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.manul_result
     *
     * @return the value of grade.manul_result
     *
     * @mbggenerated
     */
    public Integer getManulResult() {
        return manulResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.manul_result
     *
     * @param manulResult the value for grade.manul_result
     *
     * @mbggenerated
     */
    public void setManulResult(Integer manulResult) {
        this.manulResult = manulResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.create_time
     *
     * @return the value of grade.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.create_time
     *
     * @param createTime the value for grade.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.update_time
     *
     * @return the value of grade.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.update_time
     *
     * @param updateTime the value for grade.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.status
     *
     * @return the value of grade.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.status
     *
     * @param status the value for grade.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.answer_json
     *
     * @return the value of grade.answer_json
     *
     * @mbggenerated
     */
    public String getAnswerJson() {
        return answerJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.answer_json
     *
     * @param answerJson the value for grade.answer_json
     *
     * @mbggenerated
     */
    public void setAnswerJson(String answerJson) {
        this.answerJson = answerJson == null ? null : answerJson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", examId=").append(examId);
        sb.append(", result=").append(result);
        sb.append(", autoResult=").append(autoResult);
        sb.append(", manulResult=").append(manulResult);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", status=").append(status);
        sb.append(", answerJson=").append(answerJson);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}