package com.ylzh.onlineexam.entity;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

public class Permission implements Serializable {
	
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    /**
     * Ȩ��id
     */
    private String permissionId;

    /**
     * Ȩ������
     */
    private String name;

    /**
     * Ȩ������
     */
    private String description;

    /**
     * Ȩ�޷���·��
     */
    private String url;

    /**
     * Ȩ�ޱ�ʶ
     */
    private String perms;

    /**
     * ����Ȩ��id
     */
    private Integer parentId;

    /**
     * ����   0��Ŀ¼   1���˵�   2����ť
     */
    private Integer type;

    /**
     * ����
     */
    private Integer orderNum;

    /**
     * ͼ��
     */
    private String icon;
    /**
     * ״̬��1��Ч; 0��Ч
     */
    private Integer status;

    private Date createTime;

    private Date updateTime;

    /**
     * @return id
     */
    public Integer getId() {
        return id;
    }

    /**
     * @param id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * ��ȡȨ��id
     *
     * @return permission_id - Ȩ��id
     */
    public String getPermissionId() {
        return permissionId;
    }

    /**
     * ����Ȩ��id
     *
     * @param permissionId Ȩ��id
     */
    public void setPermissionId(String permissionId) {
        this.permissionId = permissionId == null ? null : permissionId.trim();
    }

    /**
     * ��ȡȨ������
     *
     * @return name - Ȩ������
     */
    public String getName() {
        return name;
    }

    /**
     * ����Ȩ������
     *
     * @param name Ȩ������
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * ��ȡȨ������
     *
     * @return description - Ȩ������
     */
    public String getDescription() {
        return description;
    }

    /**
     * ����Ȩ������
     *
     * @param description Ȩ������
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * ��ȡȨ�޷���·��
     *
     * @return url - Ȩ�޷���·��
     */
    public String getUrl() {
        return url;
    }

    /**
     * ����Ȩ�޷���·��
     *
     * @param url Ȩ�޷���·��
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    public String getPerms() {
        return perms;
    }

    public void setPerms(String perms) {
        this.perms = perms;
    }

    /**
     * ��ȡ����Ȩ��id
     *
     * @return parent_id - ����Ȩ��id
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * ���ø���Ȩ��id
     *
     * @param parentId ����Ȩ��id
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public Integer getOrderNum() {
        return orderNum;
    }

    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }

    public String getIcon() {
        return icon;
    }

    public void setIcon(String icon) {
        this.icon = icon;
    }

    /**
     * ��ȡ״̬��1��Ч��2ɾ��
     *
     * @return status - ״̬��1��Ч��2ɾ��
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * ����״̬��1��Ч��2ɾ��
     *
     * @param status ״̬��1��Ч��2ɾ��
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * @return create_time
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * @param createTime
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", permissionId=").append(permissionId);
        sb.append(", name=").append(name);
        sb.append(", description=").append(description);
        sb.append(", url=").append(url);
        sb.append(", perms=").append(perms);
        sb.append(", parentId=").append(parentId);
        sb.append(", type=").append(type);
        sb.append(", orderNum=").append(orderNum);
        sb.append(", icon=").append(icon);
        sb.append(", status=").append(status);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}